swagger: '2.0'
info:
  title: Ovy Server
  description: Backend of the Ovy App
  version: '1.0'
schemes: [https]
securityDefinitions:
  Bearer:
    name: Authorization
    type: apiKey
    in: header
    description: |
      Create a /authentication/ resource and use the token value to authorize requests on behalf of an user.
      The auth token must be provided in the Authorization header, prefixed with `Bearer `.
consumes: [application/json]
produces: [application/json]

definitions:
  EmptyResponse:
    type: object
    additionalProperties: false

  ErrorResponse:
    type: object
    properties:
      status_code:
        type: integer
        description: The HTTP error-code
      message:
        type: string
        description: Error-message to de displayed to the user
      description:
        type: string
        nullable: true
        description: (Possibly technical) description of the error to be interpreted by developers
    required: [status_code, message, description]
    additionalProperties: false

  ChildModel:
    type: object
    properties:
      birthday:
        type: string
        nullable: false
        format: date
        example: 2016-07-02
        description: The child birth date
      gender:
        type: string
        nullable: true
        enum: [ male, female, nonBinary ]
        description: The child gender
        example: female
      weight:
        type: integer
        nullable: true
        example: 360
        description: The child weight in grams
      breastfeeding:
        type: string
        nullable: true
        enum: [ 'no', 'partial', 'full' ]
        description: The status of child breastfeeding
        example: partial

  AccountModel:
    type: object
    properties:
      signedContractVersion:
        type: string
        example: 20180525
        description: The contract version signed by the user
      email:
        type: string
        format: email
        pattern: ^[^@]+@[^@]+\.[^@]+$
        example: hallo@ovyapp.com
        description: The user's email-address
      firstname:
        type: string
        minLength: 0
        maxLength: 100
        default: ''
        example: Eva
        description: The user's first name
      lastname:
        type: string
        minLength: 0
        maxLength: 100
        default: ''
        example: Mueller
        description: The user's family name
      verified:
        type: boolean
        example: true
        description: If the user's email was verified
      purpose:
        type: string
        enum: [cycleTracking, cycleTrackingNFP, wishForChild]
        nullable: true
        example: cycleTracking
        description: |
          The reason the user uses the app. Using `cycleTrackingNFP` the fertility calculation will be strictly
          according to NFP (Natural family planning) method. Otherwise an extension of this method will be applied.
      children:
        type: array
        items:
          $ref: '#/definitions/ChildModel'

        nullable: true
        example: [ { 'birthday': '2016-07-02', 'gender': 'female', 'weight': 430, 'breastfeeding': partial },
                   { 'birthday': '2016-07-03', 'gender': 'male', 'weight': 370, 'breastfeeding': no} ]
        description: Children of the requesting user

      cycleLengthPredicted:
        type: integer
        minimum: 16
        maximum: 56
        nullable: true
        example: 22
        description: The user's predicted circle length
      ovulationDayPredicted:
        type: integer
        minimum: 1
        maximum: 55
        nullable: true
        example: 14
        description: The user's predicted ovulation day within a cycle
      cycleLength:
        type: integer
        minimum: 16
        maximum: 56
        nullable: true
        example: 22
        description: The user's circle length
      cycleLengthKnown:
        type: boolean
        nullable: true
        example: true
        description: If the circle length is known to the user
      lastPeriodBegin:
        type: string
        format: date
        nullable: true
        example: 2012-12-31
        description: The start date of the user's last period
      lastPeriodLength:
        type: integer
        minimum: 1
        maximum: 10
        nullable: true
        example: 4
        description: The length of the user's last period
      lastPeriodKnown:
        type: boolean
        nullable: true
        example: true
        description: If length of the last period is known to the user
      contraceptive:
        type: boolean
        nullable: true
        example: false
        description: If the user is on birth control
      contraceptiveUpToLastCycle:
        type: boolean
        nullable: true
        example: false
        description: If the user was on birth control up to last cycle
      dateOfBirth:
        type: string
        format: date
        nullable: true
        example: 2012-12-31
        description: When the user was born
      basalThermometer:
        type: boolean
        example: true
        nullable: true
        description: If a basal thermometer is available for use
      bluetoothThermometer:
        type: boolean
        example: true
        nullable: true
        description: If a blueooth basal thermometer is available for use
      dailyReminder:
        type: boolean
        nullable: true
        example: true
        description: If daily reminders to measure the temperature shall be sent
      dailyReminderTime:
        type: string
        format: time
        nullable: true
        example: 09:30:00
        description: The time when daily reminders to measure the temperature shall be sent
      fcmToken:
        type: string
        nullable: true
        example: dlkj2htlbgn894
        description: Token to sent FCM notifications to
      locale:
        type: string
        nullable: true
        example: en_US
        description: The user's locale
      timezone:
        type: string
        format: timezone
        example: Europe/Berlin
        description: The user's timezone
      newsOptIn:
        type: boolean
        nullable: true
        description: Whether user opted into receiving news
      activatedTrialOn:
        type: string
        format: date
        nullable: true
        example: 2012-12-31
        description: When trial was activated
      forceActivatePremium:
        type: boolean
        example: false
        description: Whether to force-activate all premium features for this user
      accountCompleted:
        type: boolean
        example: true
        description: |
          true if cycleLengthKnown, lastPeriodKnown, and contraceptive are set
    required: [email, firstname, verified, purpose, cycleLengthPredicted, cycleLength, cycleLengthKnown,
               lastPeriodBegin, lastPeriodLength, lastPeriodKnown, contraceptive, dateOfBirth, basalThermometer,
               dailyReminder, dailyReminderTime, fcmToken, locale, timezone, accountCompleted]
    additionalProperties: false

  AuthenticationModel:
    type: object
    properties:
      token:
        type: string
        example: 3326f8d8d196d6e111caac17431efcdba36fefab5dbab7655b88e6
        description: Auth-token to use for authenticated requests
    required: [token]
    additionalProperties: false

  CycleDayModel:
    type: object
    properties:
      date:
        type: string
        format: date
        example: 2016-01-22
        description: The date the data refers to
      abortion:
        type: boolean
        example: false
        description: |
          Only relevant in pregnancy cycles: whether pregnancy was aborted (including miscarriage)
      temperature:
        type: number
        minimum: 32.0
        maximum: 43.99
        nullable: true
        example: 37.0
        description: |
          The basal temperature should be measured every day at the same time, e.g. directly after getting up.
          This is a major indicator that helps determine if ovulation has occurred.
      temperatureTime:
        type: string
        format: time
        nullable: true
        example: 07:00:00
        description: At which time the temperature measurement was done.
      ignoreTemperature:
        type: boolean
        example: false
        description: |
          Should the temperature measurement be ignored due to interference factors like stress, illness, etc.?
      temperatureLocation:
        type: string
        enum: [oral, vaginal, rectal]
        nullable: true
        example: oral
        description: Where the temperature was measured.
      bluetoothTemperatures:
        type: array
        items:
          type: object
          properties:
            time:
              type: string
              format: time
              example: 14:07:22
              description: When the temperature was taken
            temperature:
              type: number
              description: The measured temperature in degrees Celsius
              example: 37.0
        nullable: true
        example: [{'temperature': 38.11, 'time': '06:25:00'}, {'temperature': 39.54, 'time': '07:40:00'}]
        description: Temperatures tracked via Bluetooth
      bleeding:
        type: string
        enum: [light, medium, heavy, spotting, newspotting, lochia]
        nullable: true
        example: medium
        description: |
          Bleeding during menstrual cycle. Light, medium, heavy bleeding happen during your period and indicate
          the beginning of your menstrual cycle.
          Due to a quick migration, spotting actually means intermenstrual bleeding and newspotting means spotting.
          Both values can happen outside of your regular period.
      startsCycle:
        type: boolean
        nullable: false
        example: true
        description: Indicates if the day starts a new cycle
      startsPregnancy:
        type: boolean
        nullable: false
        example: true
        description: Indicates if the day starts a pregnancy
      ovulationPredicted:
        type: boolean
        nullable: true
        example: false
        description: Indicates if the ovulation is predicted for this date
      ovulationDetected:
        type: boolean
        nullable: true
        example: false
        description: Indicates if the ovulation is detected from bio marker for this date (e.g. based on temp graph)
      ovulationProbability:
        type: number
        example: 1.0
        description: Indicates the probability (values between 0 and 1) of ovulation on this day for coloring in the graph. A probability > 0 is only set if an actual ovulation could be detected.
      contraceptiveChangedTo:
        type: boolean
        nullable: true
        example: false
        description: If the user is on hormonal birth control
      temperatureDayNumber:
        type: integer
        nullable: true
        example: 1
        description: The day number for temperature method. The low days are marked 6..1 and the high days -1..-3 (or -4) and possibly with missing or 0 days in between.
      mucusDayNumber:
        type: integer
        nullable: true
        example: 1
        description: The day number for cervical mucus, where H123 is represented as 1234
      cervixDayNumber:
        type: integer
        nullable: true
        example: 1
        description: The day number for cervix (123)
      fertilityPredicted:
        type: string
        enum: [low, medium, high, veryHigh]
        nullable: true
        example: medium
        description: Indicates chance of pregnancy predicted for this date or null if unknown.
      periodPredicted:
        type: boolean
        nullable: true
        example: false
        description: Indicates if period is predicted for this date
      cervicalFluid:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [dry, creamy, eggWhite, watery, spinnable]
        nullable: true
        example: [dry]
        description: Tracking cervical fluid during menstrual cycle helps determine if ovulation has occurred.
      cervicalMucus:
        type: string
        enum: ['t', '0', 'f', '(S)', 'S', '(S+)', 'S+']
        nullable: true
        example: t
        description: Tracking cervical mucus during menstrual cycle helps determine if ovulation has occurred.
      vaginalFeeling:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [nothing, dry, wet, watery, slippery, sore, itchy]
        nullable: true
        example: [dry]
        description: Tracking vaginal feeling.
      vaginalAppearance:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [nothing, creamy, white, notSpinnable, clumpy, clear, glassy, spinnable]
        nullable: true
        example: [creamy]
        description: Tracking vaginal appearance.
      cervixOpening:
        type: string
        enum: [closed, partial, open]
        nullable: true
        example: closed
        description: Tracking opening of cervix.
      cervixTightness:
        type: string
        enum: [soft, hard]
        nullable: true
        example: soft
        description: Tracking tightness of cervix.
      cervixPosition:
        type: string
        enum: [low, middle, high]
        nullable: true
        example: low
        description: Tracking position of cervix.
      midpain:
        type: string
        enum: ["yes", "left", "right"]
        nullable: true
        example: "left"
        description: Tracking midpain
      breastSymptom:
        type: boolean
        example: false
        description: Signifies breast symptom
      dayInCycle:
        type: integer
        minimum: 1
        nullable: true
        example: 1
        description: The number of the day in the current cycle
      daysUntilNextCyclePredicted:
        type: integer
        minimum: 0
        nullable: true
        example: 12
        description: Number of days until the next cycle begins
      hygieneProducts:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [tampon, pad, pantyLiner, menstruationCup]
        nullable: true
        example: [tampon]
        description: What kinds of hygiene products have been used
      intercourse:
        type: string
        enum: [unprotected, protected]
        nullable: true
        example: unprotected
        description: What kind of intercourse happened
      libido:
        type: string
        enum: [high, low]
        nullable: true
        example: increased
        description: Whether your libido is unusual
      ovulationTest:
        type: string
        enum: [positive, negative]
        nullable: true
        example: invalid
        description: The result of an ovulation test made
      pregnancyTest:
        type: string
        enum: [positive, negative]
        nullable: true
        example: negative
        description: The result of a pregnancy test made
      pain:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [abdominalPain, nausea, tenderBreasts, headache, dizziness, bloating, constipation, diarrhoea, cramps]
        nullable: true
        example: [nausea]
        description: What kinds of pain occured during the day
      illness:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [fever, cold, migraine, allergy, injury, depression]
        nullable: true
        example: [migraine]
        description: What kinds of illness occured during the day
      medication:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [thyroidHormones, antidepressants, antibiotics, insulin, allergyMedication, painKillers, sleepingPills, afterPill]
        nullable: true
        example: [thyroidHormones]
        description: What medications were taken during the day
      minutesOfSleep:
        type: integer
        nullable: true
        example: 560
        description: How many minutes the user slept
      sleepDisorder:
        type: boolean
        nullable: true
        example: false
        description: Was the sleep disordered?
      activities:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [enduranceSports, athleticSports, meditation, yoga]
        nullable: true
        example: [meditation]
        description: What activities were done during the day
      interferences:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [alcohol, drugs, nightSweats, nightFreeze, travelling, stress, exhaustion,
                 lateSleep, lateDinner, partyingLate]
        nullable: true
        example: [travelling]
        description: What interferences happened during the day
      emotions:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [stressed, satisfied, irritable, panic, funny, sensitive, sad,
                 euphoric, balanced, dissatisfied, anxious]
        nullable: true
        example: [satisfied]
        description: The emotions occured during the day
      skin:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [normal, glow, dry, oily, spots, acne]
        nullable: true
        example: [good]
        description: How your skin was during the day
      hair:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [normal, dry, oily, frizzy, splitEnds, loss]
        nullable: true
        example: [good]
        description: How your hair was during the day
      notes:
        type: string
        maxLength: 500
        nullable: true
        example: Today was a happy day!
        description: Arbitrary notes
    required: [date]
    additionalProperties: false
